<?php

namespace AppBundle\Repository;

/**
 * BooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooksRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAllLoan() {
	    $qb = $this->createQueryBuilder('l');

	    $qb->where('l.customer is not null');

    	return $qb->getQuery()->getArrayResult();
}
}
