<?php

namespace AppBundle\Repository;
use AppBundle\AppBundle;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Book;

/**
 * BooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooksRepository extends EntityRepository
{

	public function getLoanedBooks(bool $loaned = true)
	{
    	#Your own logic

        return $this->findBy([
            'loans' => $loaned
        ]);
        /*return this->$this->getEntityManager()
            ->createQuery(
                'SELECT $loaned FROM AppBundle:Book $loaned'
            )
            ->getResult();*/
        /*$loan = $this->getentitymanager()
        ->getrepository('appbundle:book')
        ->findby(array($loaned))
        ->getresult();

        return $loan;*/
		
	}
}
