<?php

namespace AppBundle\Repository;

/**
 * CustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLoanRecords(int $id)
    {
        $qb = $this->createQueryBuilder('c');

        $qb ->leftJoin('c.books', 'books')
            ->addSelect('books')
            ->where('c.id = :ID')
            ->setParameter('ID', $id)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
